# Generated by Django 5.2.8 on 2025-11-30 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.PositiveIntegerField()),
                ('product_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spealist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_specialist', models.CharField(max_length=200)),
                ('lastName_specialist', models.CharField(max_length=200)),
                ('cc_specialist', models.PositiveIntegerField()),
                ('phone_specialist', models.PositiveIntegerField()),
                ('adress_specialist', models.TextField()),
                ('email_specialist', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=100)),
                ('is_enable', models.BooleanField()),
                ('descripcion_service', models.TextField()),
                ('price_service', models.PositiveIntegerField()),
                ('id_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.spealist')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.PositiveBigIntegerField()),
                ('date_register', models.DateTimeField()),
                ('date_service', models.DateField()),
                ('is_enable', models.BooleanField()),
                ('hour_service', models.TimeField()),
                ('name_pet', models.CharField(max_length=550)),
                ('descripcion_service', models.TextField()),
                ('tipe_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.tipeservice')),
            ],
        ),
    ]
